# Testing checks via PRs
name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check styling
        run: npm run eslint

      - name: Run Tests
        run : npm run test

      - name: Build production files
        run: npm run build   # 👈 build here, before e2e

      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000 # port 5000 for Actions, deploy doesn't run tests at the moment.

      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}