name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Share current date
        run: |
          echo "Current Date is: "
          date

      - name: Share current directory
        run: |
          echo "Directory files listed: "
          ls -l
